name: Build Kivy APK

on:
  # Triggers the workflow on push or pull request events on the main branch
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    # The job runs on an Ubuntu virtual machine
    runs-on: ubuntu-latest

    # Steps involved in the build job
    steps:
      # Checkout the repository
      - name: Checkout the code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Specify the Python version required by your app

      # Install Buildozer and Cython
      - name: Install Buildozer and dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ccache git libncurses5 unzip zlib1g-dev lib32z1 openjdk-11-jdk
          pip install --upgrade pip setuptools
          pip install buildozer cython virtualenv

      # Create virtual environment
      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Build the APK
      - name: Build the APK
        run: |
          buildozer android debug

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-apk
          path: build/outputs/apk/debug/*.apk
